# Generated by Django 6.0.1 on 2026-03-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.URLField(unique=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('scholarship', 'Scholarship'), ('internship', 'Internship'), ('fellowship', 'Fellowship'), ('contest', 'Contest/Award')], default='scholarship', max_length=50)),
                ('deadline', models.CharField(blank=True, max_length=100, null=True)),
                ('date_scraped', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
