# Generated by Django 6.0.1 on 2026-03-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='thumbnail',
            new_name='image_url',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='deadline',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='category',
            field=models.CharField(choices=[('scholarship', 'Scholarship'), ('internship', 'Internship'), ('fellowship', 'Fellowship'), ('contest', 'Contest/Award'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='date_scraped',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
