# Generated by Django 6.0.1 on 2026-01-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niche',
            name='name',
            field=models.CharField(choices=[('writing', 'Writing, Cultural & Creative Arts'), ('science', 'Science, Technology & Engineering'), ('academia', 'Academia & Scholarships'), ('health', 'Health, Medicine & Nursing')], max_length=100, unique=True),
        ),
    ]
