name: Trigger Scraper
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Scraper Endpoint
        run: |
          curl -X POST https://launch-gate-backend.vercel.app/api/trigger-scrape/ \
          -H "Authorization: Bearer ${{ secrets.SCRAPER_TOKEN }}"